### ISSUE TITLE
Folder to Zip

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#110]
## Description
Write a script to convert a folder to a zip file

## Technologies and Languages

- Python

Any other language and technology is also fine

## Aditional Work 
Make a GUI for this application

**Comment by gkydev** [comment]
Hi can you assign this to me please

**Comment by bislara** [comment]
@gkydev  Hey, I belive in first come, first assign. So , I will assign it to @Double77x . If he is unable to complete this, then, I will see ur PR and merge it.
