### ISSUE TITLE
Internet Speed test

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#111]
## Description
Write a script to find the below details

- [ ] Upload Speed 
- [ ] Download Speed
- [ ] Ping 

## Technologies and Languages
- Python

Any other language and technology is also fine

## Aditional Work 
Make a GUI for this

**Comment by devanaggarwal** [comment]
Can i work on this issue?

**Comment by Frans06** [comment]
can you assign to me?

**Comment by bislara** [comment]
Hey @Frans06 , I believe in first come first assign. So, I am assigning this to @devanaggarwal . If he/she is not able to complete it, then, you can move ahead with this.

**Comment by jp2373** [comment]
Can you assigne it to me later on if they can't do it?

**Comment by bislara** [comment]
Okay
