### ISSUE TITLE
Movie Recommendation System

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#112]
## Description
Write script to recommend a list of movies based on the genres liked by the user. Give the option to select genres like drama, musical, family, thriller, sport, etc

Hint - Scrap the IMDB page to get the results from it

## Technologies and Languages

- Python

Any  other language and technology is also fine

## Aditional Work 
Make a GUI for this

**Comment by mdegis** [comment]
hi, I would like to work on this 🕵️‍♂️

**Comment by bislara** [comment]
Sure. Go ahead👍
