### ISSUE TITLE
PDF Watermarker

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#113]
## Description
Add watermark to every page of the PDF or to a specific page (ask the user to give the page number as input)

## Technologies and Languages

- Python

Any other language and technology are welcomed.

## Aditional Work 
Make a GUI for this

**Comment by Frans06** [comment]
Can you assign to me?

**Comment by bislara** [comment]
sure

**Comment by jp2373** [comment]
Please assign this to me if person before me can't do it.

**Comment by bislara** [comment]
@jp2373  Sure 👍
