### ISSUE TITLE
QUIZ App

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#116]
## Description
Make a quiz app that shows question to the user and takes the answer as input.
Finally in the end, show the score to the user, by checking the correct answer.
Store the questions and answers in a CSV file. 

Make a GUI for this application

## Technologies and Languages

- Python
- Javascript

Any other language and technology is also welcomed.

**Comment by Atharva8** [comment]
Can I Please work on this?

**Comment by bislara** [comment]
Sure. Go ahead

**Comment by sark-2110** [comment]
I have worked in javascript regarding this quiz app. Can you assign me this? So that I can make a pull valid request.

**Comment by bislara** [comment]
Hey, @sark-2110 Its already been assigned. After he/she completes this and if I see u can improve it or add better code for it, Then, I will assign it to u and you can work on it.  Sounds good?

**Comment by sark-2110** [comment]
okay I have already made a good QUIZ app for this. Hence was asking for it.

**Comment by bislara** [comment]
Great. I will look into this after he completes.
