### ISSUE TITLE
PDF Encryption

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#117]
## Description
Encrypt a PDF with a password (Take input from the user)

## Technologies and Languages

- Python

Any other language and technology is also welcomed

## Aditional Work 
Make a GUI for this application

**Comment by GSantos23** [comment]
I am interested in this one. 

The GUI is mandatory for this Issue or for subsequent issues?

**Comment by bislara** [comment]
GUI is not mandatory but It will be better if  you make one.

**Comment by maxily1** [comment]
Hey, Could you assign me?

**Comment by bislara** [comment]
Hey @maxily1  Its already been assigned. If he/she doesn't complete this, then I can assign you. 

Also, you can create new issues if you want to work on something.

**Comment by bislara** [comment]
@GSantos23   Any progress?

**Comment by GSantos23** [comment]
Hi @bislara , you can assign this to @maxily1 . I am not working on this.

**Comment by bislara** [comment]
Okay. @maxily1  Would you like to take this now?

**Comment by maxily1** [comment]
Ugh, Sure, I think so. :D

**Comment by UbadahJ** [comment]
@bislara This issue seems simple so just assign this to me

**Comment by bislara** [comment]
Cool. Go ahead 🎉
