### ISSUE TITLE
Issue Labeler Action

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#12]
## Description
Add a GitHub action to label the issues with relevant labels (Ex - add different languages label from the issue description)

## Technologies and Languages
JS, GitHub Actions, and workflows

**Comment by malathit** [comment]
Shall I work on this for the **Hacktoberfest**? Can you explain what kind of labels to add? May be a list of labels?

**Comment by bislara** [comment]
Hey, actually I was working on this. I forgot to assign it to me. And the work is almost done. I will be creating a PR soon. 
Maybe you can try [this](https://github.com/bislara/code-n-stitch/issues/24) out or any other [issues](https://github.com/bislara/code-n-stitch/issues/) 
You can also create your own issue and work on it. 🤟
