### ISSUE TITLE
Wallpaper Changer

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#131]
## Description
Script to change the desktop wallpaper according to the image/images provided by the user. If multiple images provided then we can have a time interval after which the wallpaper will change. 

## Technologies and Languages

- Python

Any other language and technology is also welcome.

## Aditional Work 
Make a GUI for this.

**Comment by gs202** [comment]
I'll be happy to do it.
Is changing the wallpaper for macOS be good enough for that?
I guess that someone will be able to extend it later to other OSs

**Comment by bislara** [comment]
It's okay. But see if you can write the code for other OS as well. Else, it's fine. I am not assigning u write now. 
But u can move ahead in writing code and creating PR

**Comment by gs202** [comment]
I guess it will be pretty is to do it for Linux and Windows as well by simply detecting the OS.
I'll do them all
