### ISSUE TITLE
Website Cloner

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#132]
## Description
Given the link of the website, download all the files required for the offline reading, storage, etc.
Web scraping used for extracting data from the websites 

## Technologies and Languages

- Python

Any other technology and language is also welcome.

**Comment by gs202** [comment]
I'll be happy to take this one.
What exactly do we want to have here? just download the whole content of the site or only specific assets?

**Comment by bislara** [comment]
All the required files to load that page of the website/ whole website.  I need to u download all those to your local system.

**Comment by bislara** [comment]
@gs202   Any progress?

**Comment by gs202** [comment]
@bislara sorry, I didn't have much time working on that.
I'll try to start working on in next week, but feel free to reassign it if there are takers

**Comment by bislara** [comment]
Okay, I am unassigning u, but still, try to complete this by next week. I would like to see your PR.

**Comment by m4dummies** [comment]
Hi @bislara how should this work, should it give only the html file in the output or should it give all the files that were used in the website?

**Comment by bislara** [comment]
all the files. associated with that page

**Comment by m4dummies** [comment]
right i have a script for that but it wont run like usual pages.

**Comment by bislara** [comment]
Ok give it a try. Let's see what it can do

**Comment by m4dummies** [comment]
All right ill give it a go.

**Comment by m4dummies** [comment]
Hi @bislara I made a pr for this too you check it out and let me know if this is what you were looking for.

**Comment by bislara** [comment]
Hey, good job. Give me some time, I will review it.
