### ISSUE TITLE
Github User details

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#14]
## Description
Script to get the details of a particular user using the GitHub API
Basic Details:-
 
- [ ] Avatar url
- [ ] URL of the profile
- [ ] Repos URL
- [ ] Location
- [ ] Email
- [ ] Bio 
- [ ] Number of private repos
- [ ] Number of public repos
- [ ] Number of followers
- [ ] Number of following

Feel free to add more relevant details of the user

## Technologies and Languages

- Python
- Javascript
- GitHub APIs

Any other language and technology is also fine

## Aditional Work 
Make a GUI for this application

**Comment by djeni98** [comment]
Hey, I am starting with PRs and github workflow. Can I try this issue? I have some experience with python

**Comment by bislara** [comment]
Sure. Go for it  👍

**Comment by rohan2734** [comment]
Hey i would like to work on this, i am good at js, is this issue assigned to someone?

**Comment by bislara** [comment]
Yes, bro, I assigned it to the person who commented first. You can try some other issues. Check it out [here](https://github.com/bislara/code-n-stitch/issues/)
