### ISSUE TITLE
leaked passwords

### ISSUE THREAD

**Issue by peteruche21** [bislara/code-n-stitch#140]
## Description
a small tool to check a password leak count

## Technologies and Languages
python

**Comment by bislara** [comment]
Great! 
can you describe little more about how you are going to do it and which passwords you are going to check?

**Comment by peteruche21** [comment]
I will use an api, and sha1 hash to check whether a password (entered by a use ) has been involved in a website that has experienced data breach
Basically any password,  ranging from easy to guess to really strong passwords
The program will get the leak or pawnAge count
https://www.google.com/url?sa=t&source=web&rct=j&url=https://haveibeenpwned.com/Passwords&ved=2ahUKEwjUhvfs8KnsAhUCrxoKHVH0B44QFjAAegQIARAB&usg=AOvVaw23m4LeZsecaUwo1A8KHxpA

**Comment by bislara** [comment]
Great. Go ahead and start working.
