### ISSUE TITLE
Covid 19-gif

### ISSUE THREAD

**Issue by bunnysworld** [bislara/code-n-stitch#153]
## Description
Wanted to plot the number of corona cases on the global map in .gif format

## Technologies and Languages
Technologies : Jupyter Notebook , DataVisualization
Languages :  Python 3.x

## Aditional Work 
Check the overview of my project [here](https://github.com/bunnysworld/c-19-gif)

**Comment by bunnysworld** [comment]
hey @bislara can you assign me with this issue

**Comment by bislara** [comment]
Sure sure. Go ahead 🤟

**Comment by maxily1** [comment]
Could you assign me?

**Comment by bislara** [comment]
Hey @maxily1  Its already been assigned. If he/she doesn't complete this, then I can assign you. 

Also, you can create new issues if you want to work on something.
