### ISSUE TITLE
URGENT: Folder restructure 📢🛠

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#155]
## Description
Create 2 folders. One for python and another javascript. 
Put all the python projects inside the python folder and same for js
Inside each language folder put a readme file having a table with the project name, description and author as columns in the table.
All the projects of that language must be listed in the table.

**Comment by TestPrab** [comment]
Hello I am interested can I do this?

**Comment by bislara** [comment]
Sure go ahead. Try to complete asap so that others can follow that style. 👍

**Comment by TestPrab** [comment]
I just changed the folder structure ...can you please look into it? then I will go ahead and make the readme file too
https://github.com/TestPrab/code-n-stitch/tree/155-folder-restructure
here is the link
