### ISSUE TITLE
Encryption Tool

### ISSUE THREAD

**Issue by maxily1** [bislara/code-n-stitch#157]
## Description
A python tool with which you can encrypt plain text into some famous algorithms and cipher such as: Morse, Base64, Hex, Caesar Cipher and etc.

## Technologies and Languages
List of all the technologies and languages which you think are required for solving this issue:
* Python
* Base64 Module
* binascii Module

## Notes
I've made already this project and thought about contributing it here, and so you can check out the project right there: [Project](https://github.com/maxily1/Encrpytion-Tool)
Sadly, it is unable to decrypt yet, but will be added ASAP.

**Comment by bislara** [comment]
Great. Wonderful. Looking forward to your PR. 
Well, you can try having the decryption as well. Try it out. To let me know if you face any issue.

**Comment by bislara** [comment]
There is a folder restructure going on. Once its over, you can start working on this.

**Comment by maxily1** [comment]
Alright! I'll try implement it ASAP.
