### ISSUE TITLE
Scrap Insta post from hashtag

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#166]
## Description
Scrap the trending Instagram posts of a particular hashtag. It must scrap the image links as well as the captions. Also better if you show the count of likes, comments, etc

## Technologies and Languages

- Python
- Javascript

Any other language and technology is welcomed

## Aditional Work 
Make a GUI for this

**Comment by bislara** [comment]
@Riken-Shah  Would you like to take this as well?

**Comment by Riken-Shah** [comment]
Sure, But It might take some time I am a little busy with exams and submission.

**Comment by bislara** [comment]
Okay, no problem. Take your time.

**Comment by Riken-Shah** [comment]
Should I add the features to this [file](https://github.com/bislara/code-n-stitch/tree/master/Python/insta-tag-media-downloader)?

**Comment by bislara** [comment]
Sure you can. Just change the name of folder then. Keep it insta_post_from_hashtag

**Comment by Riken-Shah** [comment]
I have pushed the change but one check is falling. What should I do?
