### ISSUE TITLE
Popular Post by Location

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#169]
## Description
Scrap the details of the popular Instagram posts of a particular location (given as input by the user). 

## Technologies and Languages

- Python
- javascript

Any other language and technology is welcomed

## Aditional Work 
Make a GUI for this

**Comment by Riken-Shah** [comment]
Hey! Can I give it a try?
Can you please assign this task to me?

**Comment by bislara** [comment]
Sure. Go ahead

**Comment by Riken-Shah** [comment]
Should I scrape the post link or download the image?

**Comment by bislara** [comment]
Well, you can try to keep the option for both.
