### ISSUE TITLE
Count down Timer 

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#173]
## Description
Design a single page site showing a count down timer for any event. 

## Technologies and Languages
- Javascript
- HTML, CSS
Any other language and technology is welcomed

**Comment by im-adithya** [comment]
Can you please assign this to me 😄

**Comment by bislara** [comment]
Sure. Go ahead ✌

**Comment by RimorRes** [comment]
Wow that was quick!

**Comment by im-adithya** [comment]
Thank You So Much!

**Comment by im-adithya** [comment]
@bislara https://im-adithya.github.io/Countdown-Timer/
Is this okay?
Also, can you please tell me in which folder I should commit?

**Comment by bislara** [comment]
Put it inside the web hacks folder. Make a new folder inside it and then put ur files. 
one more thing, the count down looks good. But one doubt I had. When I set the time. it is not showing the countdown from my current time. 
Also, when the countdown is going on and again i press on start, Its showing both countdown and reset also not working properly in that case. 
Please look into these

**Comment by im-adithya** [comment]
Thanks for pointing out! I have made the changes and uploaded to the folder. PR has been generated. Thanks again!
