### ISSUE TITLE
Card Slider

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#179]
## Description
Make an attractive and unique card slider for a site. 

## Technologies and Languages

- Javascript, HTML, CSS

**Comment by ritviksharma3** [comment]
Hey ! Please assign me this, I'm planning to make a 3D card slider. Also, if you have anything in mind, do let me know.

**Comment by bislara** [comment]
3D one..great..go ahead with it.

**Comment by ritviksharma3** [comment]
@bislara I've added the Card Slider Feature. Please Review #190 
Also, if you want any changes to be made, please ping me here itself. 
Happy Hacktober !

**Comment by ritviksharma3** [comment]
@bislara I have added the text as well. Please Review PR#190 for issue #179 again.
