### ISSUE TITLE
Clock Application

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#182]
## Description
Make an application for clock having features like:-

- [ ] Show the current time
- [ ] Stop watch 
- [ ] Timer

It's better if you can make a simple GUI for this

## Technologies and Languages

- Python
- Javascript

Any other language and technology is also welcomed.

**Comment by gill876** [comment]
Hello there. Can I use Tkinter?

**Comment by bislara** [comment]
Sure Go ahead 👍

**Comment by bislara** [comment]
Hey @gill876  any update? Do let me know if you need any help

**Comment by gill876** [comment]
> Hey @gill876  any update? Do let me know if you need any help

OMG I had midsemesters and I really wanted to work on it but didn't get to... And I missed Hacktober Fest... I don't mind working on it still if it's available

**Comment by bislara** [comment]
Yes you can work on this now as well.

**Comment by gill876** [comment]
> No problem, you can work on this now as well.

I'd really like to work on it but I am so overwhelmed given that it's the end of semester and a lot of projects and exam preparations are to be done. I apologize for the delay. You could unassign the project from me but I still look forward to continue if it is still open when I'm free.

**Comment by bislara** [comment]
I understand, even I am having sem exams right now. Well, you can do it after your sems are over. It's okay.

**Comment by luccas13** [comment]
Hi, can you assign me this task if it's still available?

**Comment by bislara** [comment]
Ya sure. @luccas13  you can proceed
