### ISSUE TITLE
English Dictionary

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#183]
## Description
Make an application for dictionary feature which will fetch the meaning of a word. 

You can make a GUI for this or make it CLI based.

## Technologies and Languages

- Python
- javascript

Any other language and technology is welcomed.

**Comment by gill876** [comment]
Hey there. Do I have to use an API? Or could I use csv files?

If I can use csv, I'm thinking of downloading from this resource:
https://www.bragitoff.com/2016/03/english-dictionary-in-csv-format/

**Comment by bislara** [comment]
Yes, u can use the csv file. No problem with that. If possible add this as well. If the word is not found in the csv. Make an API call and get the meaning.
