### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#193]
## Description
Make a simple page that shows the weather of a city. Take the city as input from the user. 

## Technologies and Languages

- HTML, CSS, JS

Feel free to use any other language and technology

**Comment by prinsusinghal** [comment]
@bislara I want to work on it. I will be using python. Assign this to me.

**Comment by bislara** [comment]
Okay cool. Go ahead. Put it in web hacks folder as we are making a webpage

**Comment by prinsusinghal** [comment]
Sure

**Comment by prinsusinghal** [comment]
@bislara review my PR: #201
