### ISSUE TITLE
URL-Shortner

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#2]
## Description 
Script to shorten an URL using TIny URL API or any other relevant way. 

- Take input an URL
- Return the shortened URL

## Technologies and Languages

- [ ] Python 
- [ ] Javascipt
- [ ] Tiny Url
- [ ] Bit.ly

**Comment by Volku** [comment]
I want to try out with this. Could you assign it for me please?

**Comment by Volku** [comment]
I am using Python3 and JavaScript ES6. Is that's okay?

**Comment by bislara** [comment]
Yeah sure. Go with it. 👍
