### ISSUE TITLE
Wifi Password Hack

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#20]
## Description
Script to get the password of all the known networks to which your device has been connected. 

- [ ] Should return the list of the network name with its corresponding password. 
- [ ] Even if it was an open network, it must be included in the list 

## Technologies and Languages

- Python

Feel free to use any other language or technology

## Aditional Work 
You can make a GUI to show the output list

**Comment by harshit-saraswat** [comment]
Hey can I do this? I can probably do a script to get wifi addresses and passwords stored on your laptop/pc. About the GUI, I can try for a minimal GUI.

**Comment by bislara** [comment]
Ya sure. Go for it 👍
