### ISSUE TITLE
A python script to generate summary for Wikipedia articles using Wikipedia API

### ISSUE THREAD

**Issue by nishan7** [bislara/code-n-stitch#200]
## Description
A python script to generate a summary for Wikipedia articles using Wikipedia REST  @API

## Technologies and Languages
Python

**Comment by bislara** [comment]
Hey @nishan7  Do u want to make something like [this](https://github.com/bislara/code-n-stitch/tree/master/Python/wikipedia_searcher) or anything different?

**Comment by nishan7** [comment]
Yes, but using API

**Comment by bislara** [comment]
Okay, Do one thing. Make a folder inside this Wikipedia_searcher folder and name the folder as "Searcher _using_API" and put your files inside it..Don't forget to add a readme file
