### ISSUE TITLE
Request for collaboration!

### ISSUE THREAD

**Issue by Arpita-25** [bislara/code-n-stitch#21]
## Description
Hi! I wanted to work on **youtube video downloader** from your **code-n-stitch** repo!

## Technologies and Languages
List of all the technologies and languages which you think are required for solving this issue

## Aditional Work 
Any optional work you want to add.

**Comment by bislara** [comment]
The issue is already present. Check this out. [#8](https://github.com/bislara/code-n-stitch/issues/5)
