### ISSUE TITLE
Angry Birds Game 

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#210]
## Description
Write codes for Angry Bird Game

## Technologies and Languages

- Python

Feel free to use any other language and technology

**Comment by hemil26** [comment]
I would like to contribute to this issue and solve it can you please assign it to me??

**Comment by hemil26** [comment]
Can you assign this issue to me? I would like to contribute to this issue and solve it!
Thank you!

**Comment by bislara** [comment]
Sure, Go ahead
