### ISSUE TITLE
Pinging Script with a mailer.

### ISSUE THREAD

**Issue by arnav-deep** [bislara/code-n-stitch#218]
## Description
A script that will continuously ping a server to see if the server is live or not and email the users of it is not live.

## Technologies and Languages
Python.

**Comment by arnav-deep** [comment]
@mdegis I have a script ready for this. If you need more details as to what the script does. Do ask. Otherwise assign or choose the issue.

**Comment by bislara** [comment]
Hi @arnav-deep, I guess u tagged the wrong person. Never mind. 
And yes, this project seems interesting. Go ahead with it. Waiting for your PR

**Comment by arnav-deep** [comment]
Hi @bislara 
Sorry about tagging the wrong person. Not sure how that happened.
Linked a PR. Get back at me for any queries.
