### ISSUE TITLE
Collapsible Side bar 

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#224]
## Description
Make a collapsible sidebar in a website. The sidebar can have different menu options and sub-options.

## Technologies and Languages
- HTML, CSS, JS
- React (preferred)

**Comment by thePlebDev** [comment]
if this is still open I can work on this.

**Comment by bislara** [comment]
Sure go ahead

**Comment by jatin-rathee** [comment]
@bislara Can you assign this to me. I am planning to add a card flip animation

**Comment by thePlebDev** [comment]
thanks!! do you have any design for it? or is it just up to me ?

**Comment by bislara** [comment]
Put it in web hacks folder. 
And there is no specific design but yes have some content in the middle and a navbar maybe and the sidebar. 
Rest designing is up to u

**Comment by thePlebDev** [comment]
with installing react. I see here, https://github.com/bislara/code-n-stitch/tree/master/Web%20Hacks/timeline . React was installed for the separate project. Is this how you want me to do it? If I do this you will have multiple versions of React on your project, this will work but seems redundant to me. Should React not be installed at a predefined root and then have all the future react projects fall under that umbrella.

**Comment by bislara** [comment]
You need to make a new folder insider web hacks and add your files there. Did u do this or put it directly inside web hacks? If not directly, then I guess this error won't come. Let me know, if still error comes I will delete those previous react config files.

**Comment by itsneelpatel** [comment]
@bislara Is this still open ?

**Comment by bislara** [comment]
@itsneelpatel yes you can go ahead. Yes, this comes under hacktoberfest. The repo is having the hacktoberfest label. 

 @thePlebDev Sorry had to unassign you due to inactivity of the assigned issue.

**Comment by itsneelpatel** [comment]
Alright thanks @bislara .
Just a few questions: do i have to use a framework like react or node? Or would it be fine if i use html,css and js?
Also do you need any specific ui? Or just some content with a working sidebar ?

**Comment by bislara** [comment]
Its preferred to do in react, but if you are not comfortable in it, then its fine to go ahead with html css js. Try to make the web page responsive. Put some creative ideas. 

There is no specific ui to follow. Just try to make it a good looking one. Add menu options and sub menus in the side menu bar.

**Comment by itsneelpatel** [comment]
Hi @bislara , where do i add the folder?

**Comment by bislara** [comment]
Add it to the web hacks folder

**Comment by itsneelpatel** [comment]
Alright, ill be making a `pr` in about 10 minutes. 
Thanks

**Comment by itsneelpatel** [comment]
@bislara im unable to make a pr, a few of the files are being rejected when i try to push the commit.

**Comment by bislara** [comment]
Could you show some Screenshot to explain the error?

**Comment by itsneelpatel** [comment]
would it work if i push a compressed file for the project? @bislara

**Comment by bislara** [comment]
No, this shouldnt be the case. I am not sure what are your issues. Could you elaborate on it please? I guess like others you should be able to push the required files.

**Comment by itsneelpatel** [comment]
Alright give me some time.
