### ISSUE TITLE
Optimization - Clock_Application.py

### ISSUE THREAD

**Issue by luccas13** [bislara/code-n-stitch#240]
## Description

There are repeating lines of code that can be simplified

Clock_Application.py
lines 51-59 / 69-77 / 87-95

## Technologies and Languages

- Python

## Aditional Work

Add a function that simplifies redundancy.

**Comment by luccas13** [comment]
Can you assign me this task?

**Comment by bislara** [comment]
Go ahead. But the optimization you could have done it directly on the previous PR right? 😅

**Comment by luccas13** [comment]
It's true, but I didn't know how to do it and I didn't want to break the code. sorry

**Comment by bislara** [comment]
Hey hey, no need to apologize for this. Its great to know that you are learning in the process and knowing new stuff. That's quite important for a developer. You can go ahead and create a PR once done 🙌🙌🎉
