### ISSUE TITLE
Javascript Calculator

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#252]
## Description
Design a webpage having a calculator in it. It should be able to perform basic operations like addition, subtraction, division, multiplication. There should be a display screen to show the results. Below is an example of the UI, feel free to make it according to you. 

> Put this under the Javascript folder of the repo

![image](https://user-images.githubusercontent.com/35392585/135706781-34ac57b1-2ec1-4eea-a97f-92587d5c1cf7.png)

## Technologies and Languages
HTML, CSS, JS
React(Optional)

## Aditional Work 
Add more functions like factorial, sin, cos, tan, log, ln, square root, square, pi, e, a^b, etc.

**Comment by devesh-2002** [comment]
Can you please assign me this issue?

**Comment by bislara** [comment]
Sure, Go ahead
