### ISSUE TITLE
Script to delete empty folders in a directory

### ISSUE THREAD

**Issue by namanshah01** [bislara/code-n-stitch#257]
## Description
Simple script to delete all the empty folders in a given directory

## Technologies and Languages
Python

## Additional Work 
None

## Comments
It will be a simple yet efficient tool to be needed when doing some file cleanup, minimizing all tedious manual work
<br>If you think this project is eligible for the repo, please assign it to me

**Comment by bislara** [comment]
Good one. Go ahead. Looking forward to see the PR soon 🚀
