### ISSUE TITLE
Screen Recorder

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#26]
## Description
Design a screen recorder app (GUI with its backend) which can capture the screen and record the screen. 

## Technologies and Languages

- Python
- PyQt or Tkinter library 

## Aditional Work 
convert the app to an executable binary file

**Comment by pgirikishore** [comment]
Can you elaborate on what you mean by backend?
If it's alright can I solve this issue as a part of Hacktoberfest?

**Comment by bislara** [comment]
By backend I meant, doing the architecture of how the screen will be recorded, not just a GUI with no functionality. 
The frontend GUI should be linked with the functionality. 
Yes, sure. you can do it for Hacktoberfest. 🤟

Also do give a star⭐  if you like the project.

**Comment by pgirikishore** [comment]
Sure! You can assign this issue to me. I will work on it.

**Comment by bislara** [comment]
Okay cool. Go ahead 👍

**Comment by pgirikishore** [comment]
Should I create a new branch or shall I merge it in the master branch?
