### ISSUE TITLE
Port Scanner using Python

### ISSUE THREAD

**Issue by namanshah01** [bislara/code-n-stitch#260]
## Description
Create a port scanner using python

## Technologies and Languages
Python

## Additional Work 
None

## Comment
If you think this script can be a valuable addition to the repo, please do assign it to me

**Comment by bislara** [comment]
Woohh!! Good going @namanshah01. Go forward with this. Looking forward to see this project. Also, please describe a little more about the project in the readme and PR.

**Comment by namanshah01** [comment]
Thank you. I'll make sure to make them more descriptive!
