### ISSUE TITLE
Email Id extractor

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#27]
## Description
Extract email addresses from the text given in the input and display all the email ids in the end

## Technologies and Languages
- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

## Aditional Work 
You can make a GUI for this application.

**Comment by kamil200** [comment]
I wanted to work on this issue.

**Comment by bislara** [comment]
Sure, Go for it. 👍

**Comment by kamil200** [comment]
should i create new folder for this issue.?

**Comment by bislara** [comment]
Yes, Make a new folder with the issue name. ex- for this issue, name the folder as "email_id_extractor"

Rest guidelines you can find [here](https://github.com/bislara/code-n-stitch/blob/master/CONTRIBUTING.md)

**Comment by TheCoderNikhil** [comment]
I want to contribute

**Comment by kamil200** [comment]
![email_extarctor1](https://user-images.githubusercontent.com/38882087/94757604-54698780-03b8-11eb-982b-35d4de6953af.png)

**Comment by kamil200** [comment]
This my first pull request. please tell me if i did anything wrong here.
