### ISSUE TITLE
Hyperlink Extractor

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#28]
## Description
Extract any Link with either HTTP or HTTPS protocol from the text given in the input and display all the links in the end.

## Technologies and Languages
- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

## Aditional Work 
You can make a GUI for this application.

**Comment by UbadahJ** [comment]
What is the procedure to get this issue?

**Comment by bislara** [comment]
If you are interested to work on this. I can assign it to you. Once assigned, then you can create your PR. ✌

**Comment by UbadahJ** [comment]
Ok, please assign it to me

**Comment by bislara** [comment]
Okay cool.

**Comment by TheCoderNikhil** [comment]
Ok, please assign it to me

**Comment by bislara** [comment]
@TheCoderNikhil  Its already assigned, Please check other issues or create your own issues. 

Happy Hacking 🙂

**Comment by bislara** [comment]
@UbadahJ  Any update? Feel free to reach out to me if you need any help.

**Comment by bislara** [comment]
@UbadahJ  Any progress?

**Comment by UbadahJ** [comment]
Sorry for the late reply, but there is already a pull request there isn't it? #31

**Comment by bislara** [comment]
Yeah sorry it was closed so.. Well can you please put the folder inside the python folder?
