### ISSUE TITLE
Phone number Extractor

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#29]
## Description
Extract all the 10 digit phone number from the text given in the input and display all the numbers at the end

## Technologies and Languages
- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

## Aditional Work 
You can make a GUI for this application.

**Comment by pgirikishore** [comment]
Can I work on this as a part of Hacktoberfest?

**Comment by DevanshD3** [comment]
I would like to implement the python version of it for hacktoberfest 2020

**Comment by TheCoderNikhil** [comment]
I would like to implement the python version of it for hacktoberfest 2020, Please Issue Me

**Comment by DevanshD3** [comment]
I am ready with the code, should I make a PR now or tomorrow? Also it would be great if you could assign it to me.

**Comment by DevanshD3** [comment]
Hey @bislara can I be assigned this issue so that I can create a PR

**Comment by bislara** [comment]
Hey guys, I basically follow the rule of First come first assign. But, as @pgirikishore is already assigned another issue, I guess its fine if I assign it to the 2nd person. So, I will go with @DevanshD3. Rest guys, you can go through other issues. Also, I will be adding more issues soon.

One thing @DevanshD3 don't create PR before you are assigned an issue. 

Happy Hacking  🙂

**Comment by DevanshD3** [comment]
@bislara should I create a PR again? Sorry for creating one without being assigned

**Comment by bislara** [comment]
No, it's fine now.  Look after this from next time ✌
