### ISSUE TITLE
Typing Speed Test

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#3]
## Description
Script to test the Typing Speed of the User

- User must be given a paragraph to see and type the same.
- Take input paragraph from the user.
- Note down the time taken for the user to write the paragraph.
- Show some congratulations message

## Technologies and Language
Open to do in any language and use any technology

**Comment by gudeliauskaspam** [comment]
Hey! I have interest in doing this and I'm going to open a PR during Hacktoberfest!
Is there already a way to take these paragraphs and display them to the user or should it be implemented?

**Comment by Tzupy** [comment]
Hello, may i work on this?

**Comment by bislara** [comment]
Ya Sure. Go for it. 👍

**Comment by iamlordutkarsh** [comment]
Hey am Interested to solve this can u assign me this

**Comment by bislara** [comment]
Sure. Go for it 👍

**Comment by TheCoderNikhil** [comment]
Hey am Interested to solve this can u assign me this

**Comment by iamlordutkarsh** [comment]
Am working on this I Will Create Pull request in October #hacktoberfest
