### ISSUE TITLE
Whatsapp message automation

### ISSUE THREAD

**Issue by saisumanthkumar** [bislara/code-n-stitch#304]
## Description
We can send thousand's of messages in whatsapp using Selenium package.

## Technologies and Languages
- python
- selenium

## Aditional Work 
Please Add Hacktoberfest label.

**Comment by saisumanthkumar** [comment]
@bislara I would like to add this ,please assign me

**Comment by prokan468** [comment]
@saisumanthkumar I am watching this Repository. Please add an issue asap so that I  can work on it.

**Comment by ShivamPande18** [comment]
Hey @bislara i would like to work on this

**Comment by bislara** [comment]
@ShivamPande18  go ahead

**Comment by ShivamPande18** [comment]
@bislara can I use another library instead of selenium? There is a much easier option to automate WhatsApp than selenium.

**Comment by bislara** [comment]
@ShivamPande18 sure u are free to use anything

**Comment by 0xYashwanth** [comment]
Hey @bislara, I have a pretty decent knowledge of python. I want to contribute to the Whatsapp message automation project. Could you please assign this to me?
Thanks for reading.

**Comment by bislara** [comment]
@0xYashwanth It's already assigned to @ShivamPande18 and he has raised a PR as well. Would request you to wait. If he is not able to complete it, I will assign it to you.
