### ISSUE TITLE
Virus using turtle lib

### ISSUE THREAD

**Issue by dishantvyas15** [bislara/code-n-stitch#315]
## Description
You just came across a misnomer! I'd like to contribute a pyscript that uses `turtle` library functions to carry out a visual simulation of a biological virus.

## Technologies and Languages
Python and Turtle library

## Aditional Note 
As the world is slowly surpassing the pandemic state, we're all together in these times 🤜🤛<br>
Requesting assignment under `hacktoberfest` label.

**Comment by pratham-bhatnagar** [comment]
Hey @dishantvyas15, Can you assign me this issue.

**Comment by dishantvyas15** [comment]
> Hey @dishantvyas15, Can you assign me this issue.
Hi @pratham-bhatnagar, I've actually requested the maintainer to assign this issue to me. Feel free to either pick some open issue or create a new one to contribute.

**Comment by bislara** [comment]
This issue sounds interesting. Go for it @dishantvyas15
