### ISSUE TITLE
Password Strength Checker

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#32]
## Description
Script to check the password given as input from a user. It should have the following requirements. 

- [ ] Minimum 8 characters in length
   Contains 3/4 of the following items:- 
- [ ] Uppercase Letters
- [ ]  Lowercase Letters
- [ ] Numbers
- [ ] Symbols

Calculate the score for the password entered and also a comment about the complexity of the password (like Too short, add some more characters)

## Technologies and Languages

- Python
- Javascript

Any other language and technology is also fine

## Aditional Work 
Make a GUI for this

**Comment by CodeSadhu** [comment]
@bislara I'd love to work on this. Can you please assign it to me?

**Comment by CodeSadhu** [comment]
@bislara Thanks! Excited to get started!

**Comment by CodeSadhu** [comment]
@bislara Do I make a new folder named Password_Checker and add it to that? Also, sorry for the newb question, but is there a time limit for this? (first time contributor)

**Comment by bislara** [comment]
Yes, Create a new folder and work on it. Go through the  [Contribution Guidelines](https://github.com/bislara/code-n-stitch/blob/master/CONTRIBUTING.md) for more information.

No bro there is no time limit, but it's better if you complete as soon as possible. It will be counted for Hacktoberfest if you complete by October.

Happy Hacking 🙂

**Comment by CodeSadhu** [comment]
@bislara Yeah I'll complete it in October only. Was asking if there's a time limit of hours (eg. 24 hrs) or sth like that. Thanks for the info! Will try to complete ASAP.

**Comment by mr-tafreshi** [comment]
I know someone is working on this issue.but iam 13 and i very very like to work on this.Can you please assign it to me?
