### ISSUE TITLE
Normalize the syntax and create rules for future commits

### ISSUE THREAD

**Issue by UbadahJ** [bislara/code-n-stitch#33]
## Description
Currently, there are no rules that define how the code is to be formatted as well as the format of the directory. This should be changed to improve the structure

The structure can be like this
- [language]
  - [project]
    - [files]

Also, there can be a specific definition for each language formatting, Like using Black for Python, Google Style for Java and Cpp, and so on

## Technologies and Languages
None

**Comment by bislara** [comment]
Yeah, This would be great. Please, go ahead with this. It would be great if done as soon as possible. 👍🤟

Also, we can have a rule for the project folder name.

**Comment by bislara** [comment]
Also, we can have a readme inside the language folder where we can have a list of projects in that language.

**Comment by UbadahJ** [comment]
Once they are merged into the master? Or by the person creating pull request?
