### ISSUE TITLE
Text from Image

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#38]
## Description
Extract Text from Image. Take input as the image file and finally display the text extracted from the image.

## Technologies and Languages

- Python
- OCR [Optical Character Recognition]

## Aditional Work 
Make a GUI to take input as the image and display the output text in the GUI.

**Comment by Samikdevel** [comment]
I will love to work on this.
Also is there a specific module for OCR or GUI that I have to use.

**Comment by bislara** [comment]
Great. 
Yeah, you can use PyQt5 or Tkinter for GUI. and module it's up to you. 
Feel free to use any technology or language.

**Comment by Samikdevel** [comment]
Ok

**Comment by Samikdevel** [comment]
This is my first time creating a pull request so please tell if I did something wrong
