### ISSUE TITLE
Invisible Cloak

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#39]
## Description
Write script for the cloak of invisibility which was used by Harry Porter to become invisible. It should make a person invisible in a live webcam. 

## Technologies and Languages

- Python
- Image Processing
- Color detection and segmentation

**Comment by shubham2704** [comment]
Hello @bislara , I would like to work on this issue. Please assign me this issue.

**Comment by bislara** [comment]
sure. go ahead
