### ISSUE TITLE
Jpg to Png convertor

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#40]
## Description
Script to convert a .jpg image to .png image format. Take input as image and output should be displayed and stored in the file system

## Technologies and Languages

- Python
- javascript

Feel free to choose any other language or technology.

## Aditional Work 
Make a GUI for this application. Also, you can do the vice versa as well (png to jpg)

**Comment by BatoolMM** [comment]
Hi, I'd like to use python. Would you mind if I give it a try, please?

**Comment by bislara** [comment]
no bro. Go ahead and try to complete this also. Should I assign it to you then?

**Comment by UjwalKandi** [comment]
Hello @bislara, I can do it. Can you assign me to this issue?

**Comment by bislara** [comment]
If you can do in both then that's superb. Otherwise any one of that is also fine.

**Comment by bislara** [comment]
Hi @UjwalKandi , Actually I believe in first come first assign. As @BatoolMM has already asked for it. I would like to know whether he will be taking it or not. If not, I will assign it to you. 

Also, that would be superb if done in both the languages. but else,, its also fine to do in any one of it.

**Comment by BatoolMM** [comment]
Hi @bislara , yes. I'll get it done if you can assign it to me, please?

**Comment by bislara** [comment]
Sure. Go ahead.
