### ISSUE TITLE
QR Scanner

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#53]
## Description
Write a script to generate QR code from given text and also to extract text from the QR code.

## Technologies and Languages

- Python

Any other language and technologies are also welcome

## Aditional Work 
Make a GUI for this

**Comment by yashqwerty1** [comment]
can you assign this work to me please

**Comment by bislara** [comment]
Okay sure.. Go ahead

**Comment by yashqwerty1** [comment]
You will surely get awesome result because i made it before also.

**Comment by bislara** [comment]
Great!. Looking forward to it

**Comment by yashqwerty1** [comment]
sorry brother you can assign this to someone else. In my Pycharm some modules are not working.

**Comment by bislara** [comment]
@yashqwerty1  did the modules work?

**Comment by yashqwerty1** [comment]
nope bro sorry it is showing no module named '' "

**Comment by bislara** [comment]
should I un-assign u then?  Well u can always give a try after wards if you are interested to do this project

**Comment by yashqwerty1** [comment]
Sure Thanks for giving me this assignment.
I am going to come back with a solution for my problem.

**Comment by Samikdevel** [comment]
I will love to work on this

**Comment by bislara** [comment]
Sure. Go ahead 👍

**Comment by Samikdevel** [comment]
Also do I have to implement Webcam capture in it.
If yes then real-time or a single photo capture

**Comment by Samikdevel** [comment]
@bislara Please reply

**Comment by bislara** [comment]
Hey sorry.
If you can implement it in real-time then it would be really great. If you are facing issues, then you can go ahead with a picture.

**Comment by Samikdevel** [comment]
Ok

**Comment by bislara** [comment]
Any update? Feel free to reach out to me if you need any help.

**Comment by bislara** [comment]
@Samikdevel  Any progress?

**Comment by Samikdevel** [comment]
Yes, Sorry for not replying.
I had some tests going on and my pc got corrupted so I have to start again.
But hopefully I will do it in 3-4 days.

**Comment by bislara** [comment]
Okay cool no problem

**Comment by Samikdevel** [comment]
Done
