### ISSUE TITLE
Paint App

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#6]
## Description 
Make a GUI/Web application to draw and paint using your cursor. It should have the following options: -

- [x] option to make choose the brush size. 
- [x] option to choose different brush colour 
- [x] option to save it as an image in any image format
- [ ] Undo (optional) 
- [ ] Clear the whole screen (optional)

## Technologies and Language

- Python
- Javascript
- PyQt5 (Recommended)
- Tkinter
- Mouse Movement Events

**Comment by pranav6670** [comment]
Can I work on this issue? Thank You!

**Comment by bislara** [comment]
Sure. Go for it. 👍

**Comment by bislara** [comment]
@all-contributors please add pranav6670 for code, doc
