### ISSUE TITLE
Dinosaur Game

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#7]
## Description
Make an application for the dinosaur game exactly similar to the game present in chrome. 

## Technologies

- Python 
- PyGame

**Comment by yash-agarwal17** [comment]
@bislara Can I work on this?

**Comment by bislara** [comment]
Sure. Go for it. 👍

**Comment by bislara** [comment]
Any update? Feel free to reach out to me if you need any help.

**Comment by bislara** [comment]
@yash-agarwal17  Any progress?

**Comment by bislara** [comment]
@yash-agarwal17  has been unassigned from the issue due to the absence of response since the last 24 hours, making this issue up for grabs for anyone interested in it.

**Comment by Ian-Yy** [comment]
Hi @bislara, I've created a PR for the dinosaur game. Please review and let me know if any changes are required. Thanks
