### ISSUE TITLE
Image Encryptor and Decryptor

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#74]
## Description
Script to encrypt a given input image and also decrypt the encrypted image.
The script can generate a random noise image as a key and then use xor bitwise operation to encrypt the image.
And use a similar reverse process to decrypt it.

## Technologies and Languages

- Python

Using any other language and technology is also welcome.

## Aditional Work 
Make a GUI for this application

**Comment by Keerthana-Thiagaraj** [comment]
Interested. Can I please take this up?

**Comment by bislara** [comment]
sure. go ahead👍

**Comment by bislara** [comment]
Any update? Feel free to reach out to me if you need any help.

**Comment by bislara** [comment]
@Keerthana-Thiagaraj   Any progress?

**Comment by bislara** [comment]
@Keerthana-Thiagaraj  has been unassigned from the issue due to the absence of response since the last 24 hours, making this issue up for grabs for anyone interested in it.

**Comment by m4dummies** [comment]
hi @bislara can u explain the project and what is supposed to be done ?

**Comment by bislara** [comment]
you have to take input as an image and encrypt the image so that one can't know what the image is all about and then using reverse algo decrypt the encrypted image to get back the original one.

**Comment by namanshah01** [comment]
Hey can I take up this issue? I plan to convert image to a string and encrypt it with a basic cipher with a key. Only with that key, will the string be decrypted and converted to image again

**Comment by bislara** [comment]
No, that's fine. @namanshah01 , Go ahead. Waiting to see some awesome work. 🎉

**Comment by namanshah01** [comment]
Sure :+1:
