### ISSUE TITLE
PDF voice reader

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#8]
## Description 
Script to extract text from the PDF and convert the text to voice. 

- [ ] Take input as the PDF location
- [ ] Extract text from PDF
- [ ] Convert the text to voice and play that

## Technologies and Languages

- Python 
- Libraries for PDF Reader and Voice Conversion

 Any other language and technology is also fine

### Optional Work
You can make a GUI for this.

**Comment by devil-cyber** [comment]
can you assigned me  I am ready to work including GUI (kivy)

**Comment by bislara** [comment]
Ya sure. Go for it. 👍

**Comment by devil-cyber** [comment]
I will draft PR  between 1oct to 3 Oct will it be fine

**Comment by bislara** [comment]
Cool. No problem. I get it. Mostly because of Hacktober fest.

**Comment by devil-cyber** [comment]
Ya right😃😃
