### ISSUE TITLE
Torrent Searcher

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#84]
## Description

- [ ] Get the torrent magnet links of the movie. 
- [ ] Get the movie name as input from the user. 
- [ ] Copy the link  to the clipboard

## Technologies and Languages

- Python
- javascript
- APIs

Any other language and technology is also fine

## Aditional Work 
Make a GUI for this application

**Comment by lara-sahoo** [comment]
Hey I would like to work on this
