### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#89]
## Description
Convert the currency value from one unit to another. 
Take the currency (FROM and TO) as input from the user.
Also, take the amount he wants to convert as input

## Technologies and Languages

- APIs
- Python
- Javascript

Any other language and technology is also fine.

## Aditional Work 
Make a GUI for this application

**Comment by vighneshdeepweb** [comment]
can u assign me this task @bislara

**Comment by anshik1998** [comment]
Hie @bislara, @vighneshdeepweb I forgot to mention to assign this ask to me. Just now, I completed up this task in CUI. Can I raise the pull request, if @vighneshdeepweb you have not started yet on this task?

**Comment by Rishabrp99** [comment]
Hey @bislara this is Rishab, Can you please assign this project to me .This is my first contribution to open source also I have the code ready. Please let me know ASAP.

**Comment by vighneshdeepweb** [comment]
buddy @anshik1998 me too started...

**Comment by anshik1998** [comment]
> buddy @anshik1998 me too started...

No issues :)Submit your one then! @vighneshdeepweb

**Comment by vighneshdeepweb** [comment]
Is it fine now @bislara
