### ISSUE TITLE
Attribute Extractor

### ISSUE THREAD

**Issue by bislara** [bislara/code-n-stitch#9]
## Description
Extract Links, Phone number, Email Address from the text given in input.

- [ ] Any Link with either HTTP or HTTPS. 
- [ ] 10 digit phone number
- [ ] Email id with any local part and any domain part
- [ ] Display the list of all the attributes

Adding more attributes are welcomed.

## Technologies and Languages

- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

### Optional Work
You can make a GUI for this application.

**Comment by t0xic0der** [comment]
Hi @bislara, nice project you have here. I would suggest fragmenting this issue into three - each for links, phone number and email address to be able to quickly find more contributors. Also, the issue title could be a bit more descriptive.

Happy hacking! :smile:

**Comment by bislara** [comment]
Thank you so much for suggesting. I will surely look into this.  😊
