### ISSUE TITLE
Python Type Converter.

### ISSUE THREAD

**Issue by vivax3794** [bislara/code-n-stitch#91]
## Description
Convert a argument to the given type, this would even support type hints.
so for example you could do `convert([1, 2, 3], typing.List[str])` and expect to get `["1", "2", "3"]` back!

## Technologies and Languages
* python

**Comment by bislara** [comment]
Can you explain little more, like what kind of input you will be taking from the user?

**Comment by vivax3794** [comment]
a more complex example might be: 
```python
convert(
   {"vivax": {"a": "123", "b": "456"}},
   Dict[str, Dict[str, int]]
)
```
output would be:
```python
{"vivax": {"a": 123, "b": 456}}
```

basically traverse the data structure given and the type hint, and convert it if possible.

**Comment by bislara** [comment]
Okay cool. Can you please say some application for this? 
I am adding projects that have some kind of application and perform certain tasks. So, I somewhat feel this is not relevant to it.

**Comment by vivax3794** [comment]
tbh you got a point, it was mainly a cool idea I had.

can't really think of a situation this would be super useful, most things can be done in a more pythonic way :/

**Comment by bislara** [comment]
Thank you so much for expressing such ideas. If you have anything else which is relevant to this repo then, go for it, and create an issue.  It doesn't matter for me whether it is a small application or a larger one. every contribution matters for me.
